# Generated by Django 3.1.2 on 2020-10-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
